// Comprehensive Doctor Who data for the interactive timeline
import type { Doctor } from './timeline-types'

export const DOCTORS: readonly Doctor[] = [
  {
    number: 1,
    name: 'First Doctor',
    actor: 'William Hartnell',
    years: '1963-1966',
    color: '#1a1a2e',
    accentColor: '#4a4a6a',
    personality: 'Mysterious, grandfatherly, occasionally irascible. The original explorer of time and space.',
    catchphrase: 'Hmm? What\'s that, my boy?',
    companions: [
      { name: 'Susan Foreman', actor: 'Carole Ann Ford', description: 'The Doctor\'s granddaughter, a Time Lord from Gallifrey', firstAppearance: 'An Unearthly Child' },
      { name: 'Barbara Wright', actor: 'Jacqueline Hill', description: 'History teacher from Coal Hill School', firstAppearance: 'An Unearthly Child' },
      { name: 'Ian Chesterton', actor: 'William Russell', description: 'Science teacher from Coal Hill School', firstAppearance: 'An Unearthly Child' },
      { name: 'Vicki', actor: 'Maureen O\'Brien', description: 'Orphan from the 25th century', firstAppearance: 'The Rescue' },
      { name: 'Steven Taylor', actor: 'Peter Purves', description: 'Astronaut stranded on Mechanus', firstAppearance: 'The Chase' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Mutant creatures in tank-like shells, bent on universal extermination', firstAppearance: 'The Daleks', notableEpisodes: ['The Daleks', 'The Dalek Invasion of Earth', 'The Chase'] },
      { name: 'Cybermen', description: 'Cybernetically augmented humanoids who remove emotion', firstAppearance: 'The Tenth Planet', notableEpisodes: ['The Tenth Planet'] },
    ],
    keyStories: [
      { title: 'An Unearthly Child', year: 1963, type: 'serial', significance: 'The very first Doctor Who story - introduces the Doctor, Susan, and the TARDIS', isLandmark: true },
      { title: 'The Daleks', year: 1963, type: 'serial', significance: 'First appearance of the Daleks, establishing the show\'s most iconic villains', isLandmark: true },
      { title: 'The Dalek Invasion of Earth', year: 1964, type: 'serial', significance: 'Susan leaves the TARDIS - first companion departure', isLandmark: true },
      { title: 'The Tenth Planet', year: 1966, type: 'serial', significance: 'First regeneration, first Cybermen appearance', isLandmark: true },
    ],
    facts: [
      'First Doctor to pilot the TARDIS',
      'Originally portrayed as more anti-heroic',
      'The character mellowed over time',
      'Established the concept of regeneration',
      'Era defined classic sci-fi storytelling',
    ],
    regenerationCause: 'Old age and exhaustion after battling the Cybermen',
  },
  {
    number: 2,
    name: 'Second Doctor',
    actor: 'Patrick Troughton',
    years: '1966-1969',
    color: '#16213e',
    accentColor: '#0f3460',
    personality: 'Whimsical, seemingly bumbling but secretly brilliant. The cosmic hobo.',
    catchphrase: 'Oh my giddy aunt!',
    companions: [
      { name: 'Jamie McCrimmon', actor: 'Frazer Hines', description: 'Scottish Highlander from 1746', firstAppearance: 'The Highlanders' },
      { name: 'Victoria Waterfield', actor: 'Deborah Watling', description: 'Victorian-era orphan', firstAppearance: 'The Evil of the Daleks' },
      { name: 'Zoe Heriot', actor: 'Wendy Padbury', description: 'Genius astrophysicist from the 21st century', firstAppearance: 'The Wheel in Space' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Continued threat throughout the era', notableEpisodes: ['The Power of the Daleks', 'The Evil of the Daleks'] },
      { name: 'Cybermen', description: 'Major recurring threat', notableEpisodes: ['The Moonbase', 'The Tomb of the Cybermen', 'The Invasion'] },
      { name: 'Ice Warriors', description: 'Reptilian Martians', firstAppearance: 'The Ice Warriors', notableEpisodes: ['The Ice Warriors', 'The Seeds of Death'] },
      { name: 'Great Intelligence', description: 'Disembodied entity using robot Yeti', notableEpisodes: ['The Abominable Snowmen', 'The Web of Fear'] },
    ],
    keyStories: [
      { title: 'The Power of the Daleks', year: 1966, type: 'serial', significance: 'First post-regeneration story, proving the show could continue', isLandmark: true },
      { title: 'The Tomb of the Cybermen', year: 1967, type: 'serial', significance: 'Classic Cybermen story, rediscovered in 1992' },
      { title: 'The Web of Fear', year: 1968, type: 'serial', significance: 'First appearance of Colonel Lethbridge-Stewart (later the Brigadier)' },
      { title: 'The War Games', year: 1969, type: 'serial', significance: 'First mention of Time Lords and Gallifrey, forced regeneration', isLandmark: true },
    ],
    facts: [
      'Introduced the sonic screwdriver',
      'First Doctor to face the Time Lords',
      'Many episodes from this era are missing',
      'Established the recorder as an iconic prop',
      'Patrick Troughton influenced many future Doctors',
    ],
    regenerationCause: 'Forced regeneration by the Time Lords as punishment for interfering',
  },
  {
    number: 3,
    name: 'Third Doctor',
    actor: 'Jon Pertwee',
    years: '1970-1974',
    color: '#1e5128',
    accentColor: '#4e9f3d',
    personality: 'Action-oriented, dashing, authoritative. A gentleman scientist and man of action.',
    catchphrase: 'Reverse the polarity of the neutron flow!',
    companions: [
      { name: 'Liz Shaw', actor: 'Caroline John', description: 'Cambridge scientist recruited by UNIT', firstAppearance: 'Spearhead from Space' },
      { name: 'Jo Grant', actor: 'Katy Manning', description: 'UNIT agent, cheerful and resourceful', firstAppearance: 'Terror of the Autons' },
      { name: 'Sarah Jane Smith', actor: 'Elisabeth Sladen', description: 'Investigative journalist who became the most beloved companion', firstAppearance: 'The Time Warrior' },
    ],
    enemies: [
      { name: 'The Master', description: 'Renegade Time Lord, the Doctor\'s nemesis', firstAppearance: 'Terror of the Autons', notableEpisodes: ['Terror of the Autons', 'The Dæmons', 'Frontier in Space'] },
      { name: 'Daleks', description: 'Continued appearances', notableEpisodes: ['Day of the Daleks', 'Planet of the Daleks', 'Death to the Daleks'] },
      { name: 'Autons', description: 'Living plastic controlled by the Nestene Consciousness', firstAppearance: 'Spearhead from Space', notableEpisodes: ['Spearhead from Space', 'Terror of the Autons'] },
      { name: 'Sontarans', description: 'Clone warrior race', firstAppearance: 'The Time Warrior', notableEpisodes: ['The Time Warrior', 'The Sontaran Experiment'] },
    ],
    keyStories: [
      { title: 'Spearhead from Space', year: 1970, type: 'serial', significance: 'First colour story, introduces UNIT era and Autons', isLandmark: true },
      { title: 'Terror of the Autons', year: 1971, type: 'serial', significance: 'First appearance of the Master', isLandmark: true },
      { title: 'The Three Doctors', year: 1972, type: 'serial', significance: '10th anniversary special, first multi-Doctor story', isLandmark: true },
      { title: 'The Green Death', year: 1973, type: 'serial', significance: 'Jo Grant\'s departure, environmental themes' },
      { title: 'Planet of the Spiders', year: 1974, type: 'serial', significance: 'Third Doctor\'s regeneration story' },
    ],
    facts: [
      'Exiled to Earth by the Time Lords',
      'Scientific advisor to UNIT',
      'First Doctor shown in colour',
      'Drove Bessie (yellow roadster) and the Whomobile',
      'Era introduced the Master as a recurring villain',
    ],
    regenerationCause: 'Radiation poisoning from the Great One\'s cave on Metebelis III',
  },
  {
    number: 4,
    name: 'Fourth Doctor',
    actor: 'Tom Baker',
    years: '1974-1981',
    color: '#6b2d2d',
    accentColor: '#9b4444',
    personality: 'Eccentric, bohemian, unpredictable. Wild-eyed and charismatic with a love of jelly babies.',
    catchphrase: 'Would you like a jelly baby?',
    companions: [
      { name: 'Sarah Jane Smith', actor: 'Elisabeth Sladen', description: 'Continued from Third Doctor era', firstAppearance: 'The Time Warrior' },
      { name: 'Harry Sullivan', actor: 'Ian Marter', description: 'UNIT medical officer', firstAppearance: 'Robot' },
      { name: 'Leela', actor: 'Louise Jameson', description: 'Savage warrior of the Sevateem tribe', firstAppearance: 'The Face of Evil' },
      { name: 'K9', actor: 'Voice: John Leeson', description: 'Robot dog computer', firstAppearance: 'The Invisible Enemy' },
      { name: 'Romana I', actor: 'Mary Tamm', description: 'Time Lady sent by the White Guardian', firstAppearance: 'The Ribos Operation' },
      { name: 'Romana II', actor: 'Lalla Ward', description: 'Romana\'s second incarnation', firstAppearance: 'Destiny of the Daleks' },
      { name: 'Adric', actor: 'Matthew Waterhouse', description: 'Young mathematical genius from E-Space', firstAppearance: 'Full Circle' },
      { name: 'Nyssa', actor: 'Sarah Sutton', description: 'Trakenite aristocrat', firstAppearance: 'The Keeper of Traken' },
      { name: 'Tegan Jovanka', actor: 'Janet Fielding', description: 'Australian air stewardess', firstAppearance: 'Logopolis' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Including their creator Davros', notableEpisodes: ['Genesis of the Daleks', 'Destiny of the Daleks'] },
      { name: 'Davros', description: 'Creator of the Daleks', firstAppearance: 'Genesis of the Daleks', notableEpisodes: ['Genesis of the Daleks', 'Destiny of the Daleks'] },
      { name: 'The Master', description: 'Continued nemesis', notableEpisodes: ['The Deadly Assassin', 'The Keeper of Traken', 'Logopolis'] },
      { name: 'Sutekh', description: 'Last of the Osirians, god-like power', notableEpisodes: ['Pyramids of Mars'] },
      { name: 'Cybermen', description: 'Returning threat', notableEpisodes: ['Revenge of the Cybermen'] },
    ],
    keyStories: [
      { title: 'Robot', year: 1974, type: 'serial', significance: 'Fourth Doctor\'s debut story' },
      { title: 'Genesis of the Daleks', year: 1975, type: 'serial', significance: 'Origin of the Daleks, introduces Davros', isLandmark: true },
      { title: 'Pyramids of Mars', year: 1975, type: 'serial', significance: 'Classic gothic horror story with Sutekh' },
      { title: 'The Deadly Assassin', year: 1976, type: 'serial', significance: 'First story set entirely on Gallifrey, no companion' },
      { title: 'City of Death', year: 1979, type: 'serial', significance: 'Written by Douglas Adams, highest-rated classic story' },
      { title: 'Logopolis', year: 1981, type: 'serial', significance: 'Fourth Doctor\'s regeneration, introduces the Watcher', isLandmark: true },
    ],
    facts: [
      'Longest-serving classic Doctor (7 years)',
      'Iconic scarf became a cultural symbol',
      'Era spanned horror, comedy, and hard sci-fi',
      'Introduced the Key to Time season arc',
      'Tom Baker remains the most recognized Doctor',
    ],
    regenerationCause: 'Fall from the Pharos Project radio telescope while battling the Master',
  },
  {
    number: 5,
    name: 'Fifth Doctor',
    actor: 'Peter Davison',
    years: '1981-1984',
    color: '#c9a227',
    accentColor: '#e6c75a',
    personality: 'Youthful, vulnerable, brave. A cricketing gentleman with a more human touch.',
    catchphrase: 'Brave heart, Tegan.',
    companions: [
      { name: 'Adric', actor: 'Matthew Waterhouse', description: 'Continued from Fourth Doctor era', firstAppearance: 'Full Circle' },
      { name: 'Nyssa', actor: 'Sarah Sutton', description: 'Continued from Fourth Doctor era', firstAppearance: 'The Keeper of Traken' },
      { name: 'Tegan Jovanka', actor: 'Janet Fielding', description: 'Continued from Fourth Doctor era', firstAppearance: 'Logopolis' },
      { name: 'Vislor Turlough', actor: 'Mark Strickson', description: 'Exiled alien posing as a schoolboy', firstAppearance: 'Mawdryn Undead' },
      { name: 'Kamelion', actor: 'Voice: Gerald Flood', description: 'Shape-shifting android', firstAppearance: 'The King\'s Demons' },
      { name: 'Peri Brown', actor: 'Nicola Bryant', description: 'American botany student', firstAppearance: 'Planet of Fire' },
    ],
    enemies: [
      { name: 'The Master', description: 'Continued nemesis, now played by Anthony Ainley', notableEpisodes: ['Castrovalva', 'Time-Flight', 'Planet of Fire'] },
      { name: 'Cybermen', description: 'Major threat in this era', notableEpisodes: ['Earthshock', 'The Five Doctors'] },
      { name: 'Daleks', description: 'Returning enemies', notableEpisodes: ['Resurrection of the Daleks'] },
      { name: 'The Black Guardian', description: 'Cosmic entity of chaos', notableEpisodes: ['Mawdryn Undead', 'Terminus', 'Enlightenment'] },
      { name: 'Silurians/Sea Devils', description: 'Earth reptiles', notableEpisodes: ['Warriors of the Deep'] },
    ],
    keyStories: [
      { title: 'Castrovalva', year: 1982, type: 'serial', significance: 'Fifth Doctor\'s debut, complex regeneration story' },
      { title: 'Earthshock', year: 1982, type: 'serial', significance: 'Death of Adric - first companion death since the 60s', isLandmark: true },
      { title: 'The Five Doctors', year: 1983, type: 'special', significance: '20th anniversary special with all five Doctors', isLandmark: true },
      { title: 'The Caves of Androzani', year: 1984, type: 'serial', significance: 'Often voted best classic story, Fifth Doctor regenerates', isLandmark: true },
    ],
    facts: [
      'Youngest actor to play the Doctor at the time (29)',
      'Wore a decorative vegetable (celery) on his lapel',
      'Era dealt with more mature themes including death',
      'First Doctor since the First to remove the sonic screwdriver',
      'Peter Davison\'s daughter Georgia later married David Tennant',
    ],
    regenerationCause: 'Spectrox toxaemia - gave the only antidote to Peri',
  },
  {
    number: 6,
    name: 'Sixth Doctor',
    actor: 'Colin Baker',
    years: '1984-1986',
    color: '#7b2cbf',
    accentColor: '#9d4edd',
    personality: 'Bombastic, arrogant, unpredictable. Abrasive exterior hiding deep compassion.',
    catchphrase: 'Mmm, I wonder...',
    companions: [
      { name: 'Peri Brown', actor: 'Nicola Bryant', description: 'Continued from Fifth Doctor era', firstAppearance: 'Planet of Fire' },
      { name: 'Melanie Bush', actor: 'Bonnie Langford', description: 'Computer programmer with photographic memory', firstAppearance: 'Terror of the Vervoids' },
    ],
    enemies: [
      { name: 'The Master', description: 'Continued nemesis', notableEpisodes: ['The Mark of the Rani'] },
      { name: 'Daleks', description: 'Major storyline', notableEpisodes: ['Revelation of the Daleks'] },
      { name: 'Sil', description: 'Greedy Mentor businessman', notableEpisodes: ['Vengeance on Varos', 'Mindwarp'] },
      { name: 'The Rani', description: 'Renegade Time Lady scientist', firstAppearance: 'The Mark of the Rani', notableEpisodes: ['The Mark of the Rani', 'Time and the Rani'] },
      { name: 'The Valeyard', description: 'Dark future incarnation of the Doctor', firstAppearance: 'The Trial of a Time Lord', notableEpisodes: ['The Trial of a Time Lord'] },
    ],
    keyStories: [
      { title: 'The Twin Dilemma', year: 1984, type: 'serial', significance: 'Sixth Doctor\'s debut - controversial start' },
      { title: 'Vengeance on Varos', year: 1985, type: 'serial', significance: 'Commentary on media violence' },
      { title: 'Revelation of the Daleks', year: 1985, type: 'serial', significance: 'Dark Dalek story with Davros' },
      { title: 'The Trial of a Time Lord', year: 1986, type: 'serial', significance: 'Season-long arc, introduces the Valeyard', isLandmark: true },
    ],
    facts: [
      'Iconic multi-coloured coat was deliberately garish',
      'Era was marked by behind-the-scenes turmoil',
      'Colin Baker was dismissed from the role',
      'Big Finish audios later rehabilitated this Doctor\'s reputation',
      'The Sixth Doctor\'s regeneration was not shown on TV',
    ],
    regenerationCause: 'Unknown attack on the TARDIS by the Rani (shown in Time and the Rani)',
  },
  {
    number: 7,
    name: 'Seventh Doctor',
    actor: 'Sylvester McCoy',
    years: '1987-1989',
    color: '#582f0e',
    accentColor: '#7f4f24',
    personality: 'Mysterious manipulator with a dark side. Clownish exterior hiding a chess master.',
    catchphrase: 'Ace!',
    companions: [
      { name: 'Melanie Bush', actor: 'Bonnie Langford', description: 'Continued from Sixth Doctor era', firstAppearance: 'Terror of the Vervoids' },
      { name: 'Ace', actor: 'Sophie Aldred', description: 'Teenage explosives expert from Perivale', firstAppearance: 'Dragonfire' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Major storylines', notableEpisodes: ['Remembrance of the Daleks'] },
      { name: 'Cybermen', description: 'Final classic series appearance', notableEpisodes: ['Silver Nemesis'] },
      { name: 'The Master', description: 'Final classic series confrontation', notableEpisodes: ['Survival'] },
      { name: 'Fenric', description: 'Evil from the dawn of time', notableEpisodes: ['The Curse of Fenric'] },
      { name: 'Gods of Ragnarok', description: 'Powerful entities', notableEpisodes: ['The Greatest Show in the Galaxy'] },
    ],
    keyStories: [
      { title: 'Time and the Rani', year: 1987, type: 'serial', significance: 'Seventh Doctor\'s debut' },
      { title: 'Remembrance of the Daleks', year: 1988, type: 'serial', significance: '25th anniversary story, returns to Coal Hill School', isLandmark: true },
      { title: 'The Curse of Fenric', year: 1989, type: 'serial', significance: 'Complex story about Ace\'s past and faith' },
      { title: 'Survival', year: 1989, type: 'serial', significance: 'Final story of the classic series', isLandmark: true },
    ],
    facts: [
      'Last Doctor of the original run',
      'Era introduced more complex storytelling',
      'Ace was a prototype for modern companions',
      'The "Cartmel Masterplan" hinted at deeper mysteries',
      'Show was cancelled in 1989 after this era',
    ],
    regenerationCause: 'Shot in a San Francisco gang crossfire, died during surgery (shown in the TV Movie)',
  },
  {
    number: 8,
    name: 'Eighth Doctor',
    actor: 'Paul McGann',
    years: '1996, 2013',
    color: '#2d6a4f',
    accentColor: '#40916c',
    personality: 'Romantic, passionate, enthusiastic. A Byron-esque adventurer.',
    catchphrase: 'I love humans. Always seeing patterns in things that aren\'t there.',
    companions: [
      { name: 'Grace Holloway', actor: 'Daphne Ashbrook', description: 'San Francisco cardiologist', firstAppearance: 'Doctor Who (TV Movie)' },
      { name: 'Charley Pollard', actor: 'India Fisher', description: 'Edwardian adventuress (Big Finish)', firstAppearance: 'Storm Warning (audio)' },
      { name: 'Lucie Miller', actor: 'Sheridan Smith', description: 'Blackpool office worker (Big Finish)', firstAppearance: 'Blood of the Daleks (audio)' },
    ],
    enemies: [
      { name: 'The Master', description: 'Executed by the Daleks, takes over a human body', notableEpisodes: ['Doctor Who (TV Movie)'] },
      { name: 'Daleks', description: 'Major presence in audios and Time War', notableEpisodes: ['The Night of the Doctor'] },
      { name: 'Time Lords', description: 'Increasingly corrupt during Time War', notableEpisodes: ['The Night of the Doctor'] },
    ],
    keyStories: [
      { title: 'Doctor Who (TV Movie)', year: 1996, type: 'movie', significance: 'Only full TV appearance, first on-screen kiss for the Doctor', isLandmark: true },
      { title: 'The Night of the Doctor', year: 2013, type: 'special', significance: 'Mini-episode showing regeneration into the War Doctor', isLandmark: true },
    ],
    facts: [
      'Only appeared in one TV movie initially',
      'Vast audio adventures with Big Finish',
      'First Doctor to kiss a companion on screen',
      'Fought in the early Time War',
      'Returned for the 50th anniversary mini-episode',
    ],
    regenerationCause: 'Crashed on Karn, temporarily died, chose to regenerate into a warrior',
  },
  {
    number: 0,
    name: 'War Doctor',
    actor: 'John Hurt',
    years: '2013',
    color: '#3d0000',
    accentColor: '#8b0000',
    personality: 'Battle-worn, weary, but still holding onto hope. The Doctor who fought.',
    catchphrase: 'No more.',
    companions: [],
    enemies: [
      { name: 'Daleks', description: 'Primary enemy in the Time War', notableEpisodes: ['The Day of the Doctor'] },
      { name: 'Time Lords', description: 'Fighting alongside but also against their corruption', notableEpisodes: ['The Day of the Doctor'] },
    ],
    keyStories: [
      { title: 'The Day of the Doctor', year: 2013, type: 'special', significance: '50th anniversary special, saves Gallifrey', isLandmark: true },
    ],
    facts: [
      'Created for the Time War',
      'Disowned the name "Doctor"',
      'Ended the Time War (or so he thought)',
      'Later discovered he saved Gallifrey',
      'John Hurt was the only actor to play a "numbered" Doctor without a full series',
    ],
    regenerationCause: 'Old age after the Time War ended',
  },
  {
    number: 9,
    name: 'Ninth Doctor',
    actor: 'Christopher Eccleston',
    years: '2005',
    color: '#023047',
    accentColor: '#219ebc',
    personality: 'Damaged survivor with manic energy. Hiding trauma behind a grin.',
    catchphrase: 'Fantastic!',
    companions: [
      { name: 'Rose Tyler', actor: 'Billie Piper', description: 'Shop worker from the Powell Estate who becomes the Doctor\'s closest friend', firstAppearance: 'Rose' },
      { name: 'Captain Jack Harkness', actor: 'John Barrowman', description: 'Time Agent and con man who becomes immortal', firstAppearance: 'The Empty Child' },
      { name: 'Mickey Smith', actor: 'Noel Clarke', description: 'Rose\'s boyfriend who grows into a hero', firstAppearance: 'Rose' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Survivors of the Time War', notableEpisodes: ['Dalek', 'Bad Wolf', 'The Parting of the Ways'] },
      { name: 'Autons/Nestene', description: 'Living plastic', notableEpisodes: ['Rose'] },
      { name: 'Slitheen', description: 'Criminal family from Raxacoricofallapatorius', notableEpisodes: ['Aliens of London', 'World War Three', 'Boom Town'] },
      { name: 'The Empty Child', description: 'Gas mask zombies', notableEpisodes: ['The Empty Child', 'The Doctor Dances'] },
    ],
    keyStories: [
      { title: 'Rose', year: 2005, type: 'episode', significance: 'Revival of Doctor Who, introduces Rose Tyler', isLandmark: true },
      { title: 'Dalek', year: 2005, type: 'episode', significance: 'First Dalek in the new series, explores Time War trauma' },
      { title: 'The Empty Child/The Doctor Dances', year: 2005, type: 'episode', significance: 'Steven Moffat\'s first episode, introduces Jack Harkness' },
      { title: 'Bad Wolf/The Parting of the Ways', year: 2005, type: 'episode', significance: 'Ninth Doctor regenerates saving Rose', isLandmark: true },
    ],
    facts: [
      'First Doctor of the revival era',
      'Only Doctor for one series',
      'Leather jacket marked a new visual style',
      'Carried trauma from the Time War',
      'Christopher Eccleston left after one series',
    ],
    regenerationCause: 'Absorbed the Time Vortex from Rose to save her life',
  },
  {
    number: 10,
    name: 'Tenth Doctor',
    actor: 'David Tennant',
    years: '2005-2010',
    color: '#5c4033',
    accentColor: '#8b6914',
    personality: 'Charismatic, emotional, brilliant. The lonely god with a human heart.',
    catchphrase: 'Allons-y!',
    companions: [
      { name: 'Rose Tyler', actor: 'Billie Piper', description: 'Continued from Ninth Doctor era', firstAppearance: 'Rose' },
      { name: 'Mickey Smith', actor: 'Noel Clarke', description: 'Continued, becomes a proper companion', firstAppearance: 'Rose' },
      { name: 'Donna Noble', actor: 'Catherine Tate', description: 'Temp worker who becomes the most important woman in the universe', firstAppearance: 'The Runaway Bride' },
      { name: 'Martha Jones', actor: 'Freema Agyeman', description: 'Medical student who walks the Earth', firstAppearance: 'Smith and Jones' },
      { name: 'Captain Jack Harkness', actor: 'John Barrowman', description: 'Returned from Torchwood', firstAppearance: 'The Empty Child' },
      { name: 'Wilfred Mott', actor: 'Bernard Cribbins', description: 'Donna\'s grandfather, the Doctor\'s friend', firstAppearance: 'Voyage of the Damned' },
    ],
    enemies: [
      { name: 'Daleks', description: 'Including Dalek Caan and the Reality Bomb', notableEpisodes: ['Doomsday', 'Daleks in Manhattan', 'The Stolen Earth', 'Journey\'s End'] },
      { name: 'Cybermen', description: 'From a parallel universe', notableEpisodes: ['Rise of the Cybermen', 'Army of Ghosts', 'Doomsday'] },
      { name: 'The Master', description: 'Harold Saxon, played by John Simm', notableEpisodes: ['Utopia', 'The Sound of Drums', 'Last of the Time Lords', 'The End of Time'] },
      { name: 'The Weeping Angels', description: 'Quantum-locked assassins', firstAppearance: 'Blink', notableEpisodes: ['Blink'] },
      { name: 'Davros', description: 'Creator of the Daleks returns', notableEpisodes: ['The Stolen Earth', 'Journey\'s End'] },
    ],
    keyStories: [
      { title: 'The Christmas Invasion', year: 2005, type: 'special', significance: 'Tenth Doctor\'s first full story' },
      { title: 'Doomsday', year: 2006, type: 'episode', significance: 'Rose trapped in parallel world', isLandmark: true },
      { title: 'Blink', year: 2007, type: 'episode', significance: 'Introduces Weeping Angels, "wibbly wobbly timey wimey"', isLandmark: true },
      { title: 'The Stolen Earth/Journey\'s End', year: 2008, type: 'episode', significance: 'Massive crossover with all companions' },
      { title: 'The End of Time', year: 2010, type: 'special', significance: 'Tenth Doctor\'s farewell, "I don\'t want to go"', isLandmark: true },
    ],
    facts: [
      'Most popular Doctor in polls for many years',
      'Famous for his Converse trainers and long coat',
      'Had a meta-crisis clone who stayed with Rose',
      'Married Elizabeth I',
      'David Tennant married Georgia Moffett (Fifth Doctor\'s daughter)',
    ],
    regenerationCause: 'Radiation poisoning from saving Wilfred Mott',
  },
  {
    number: 11,
    name: 'Eleventh Doctor',
    actor: 'Matt Smith',
    years: '2010-2013',
    color: '#4a0e4e',
    accentColor: '#9b4dca',
    personality: 'Ancient soul in a young body. Mad, childlike, but deeply old.',
    catchphrase: 'Geronimo!',
    companions: [
      { name: 'Amy Pond', actor: 'Karen Gillan', description: 'The girl who waited, knew the Doctor since childhood', firstAppearance: 'The Eleventh Hour' },
      { name: 'Rory Williams', actor: 'Arthur Darvill', description: 'Amy\'s husband, the Last Centurion', firstAppearance: 'The Eleventh Hour' },
      { name: 'River Song', actor: 'Alex Kingston', description: 'The Doctor\'s wife, archaeologist from the future', firstAppearance: 'Silence in the Library (Tenth Doctor)' },
      { name: 'Clara Oswald', actor: 'Jenna Coleman', description: 'The Impossible Girl, echoed throughout the Doctor\'s timeline', firstAppearance: 'Asylum of the Daleks' },
    ],
    enemies: [
      { name: 'The Silence', description: 'Religious order you forget when you look away', notableEpisodes: ['The Impossible Astronaut', 'Day of the Moon', 'The Wedding of River Song'] },
      { name: 'Daleks', description: 'New paradigm and Asylum', notableEpisodes: ['Victory of the Daleks', 'Asylum of the Daleks'] },
      { name: 'Weeping Angels', description: 'Major threat', notableEpisodes: ['The Time of Angels', 'Flesh and Stone', 'The Angels Take Manhattan'] },
      { name: 'The Great Intelligence', description: 'Returns from classic series', notableEpisodes: ['The Snowmen', 'The Name of the Doctor'] },
      { name: 'Madame Kovarian', description: 'Leader of the Silence', notableEpisodes: ['A Good Man Goes to War', 'The Wedding of River Song'] },
    ],
    keyStories: [
      { title: 'The Eleventh Hour', year: 2010, type: 'episode', significance: 'Eleventh Doctor\'s debut, introduces Amy', isLandmark: true },
      { title: 'The Pandorica Opens/The Big Bang', year: 2010, type: 'episode', significance: 'Universe rebooted, Rory as Centurion' },
      { title: 'The Day of the Doctor', year: 2013, type: 'special', significance: '50th anniversary, Gallifrey saved', isLandmark: true },
      { title: 'The Time of the Doctor', year: 2013, type: 'special', significance: 'Eleventh Doctor ages and regenerates at Trenzalore', isLandmark: true },
    ],
    facts: [
      'Youngest actor to play the Doctor (26)',
      'Famous for bow ties and fezzes',
      'Spent 900 years defending Trenzalore',
      'Married River Song',
      'Granted a new regeneration cycle by Gallifrey',
    ],
    regenerationCause: 'Old age on Trenzalore, after receiving new regenerations from Gallifrey',
  },
  {
    number: 12,
    name: 'Twelfth Doctor',
    actor: 'Peter Capaldi',
    years: '2014-2017',
    color: '#1a1a2e',
    accentColor: '#4a4e69',
    personality: 'Fierce, uncompromising, punk rock. Searching for whether he\'s a good man.',
    catchphrase: 'Am I a good man?',
    companions: [
      { name: 'Clara Oswald', actor: 'Jenna Coleman', description: 'Continued from Eleventh Doctor, became reckless', firstAppearance: 'Asylum of the Daleks' },
      { name: 'Danny Pink', actor: 'Samuel Anderson', description: 'Former soldier, Clara\'s boyfriend', firstAppearance: 'Into the Dalek' },
      { name: 'Bill Potts', actor: 'Pearl Mackie', description: 'University cafeteria worker, first openly gay main companion', firstAppearance: 'The Pilot' },
      { name: 'Nardole', actor: 'Matt Lucas', description: 'Cyborg assistant with a mysterious past', firstAppearance: 'The Husbands of River Song' },
    ],
    enemies: [
      { name: 'Missy', description: 'The Master regenerated as a woman, Michelle Gomez', notableEpisodes: ['Dark Water', 'Death in Heaven', 'World Enough and Time'] },
      { name: 'Daleks', description: 'Continued threat', notableEpisodes: ['Into the Dalek', 'The Witch\'s Familiar'] },
      { name: 'Cybermen', description: 'Major finale threats', notableEpisodes: ['Dark Water', 'Death in Heaven', 'World Enough and Time', 'The Doctor Falls'] },
      { name: 'Davros', description: 'Dying confrontation', notableEpisodes: ['The Magician\'s Apprentice', 'The Witch\'s Familiar'] },
      { name: 'The Master (John Simm)', description: 'Returns alongside Missy', notableEpisodes: ['World Enough and Time', 'The Doctor Falls'] },
    ],
    keyStories: [
      { title: 'Deep Breath', year: 2014, type: 'episode', significance: 'Twelfth Doctor\'s debut' },
      { title: 'Listen', year: 2014, type: 'episode', significance: 'Explores the Doctor\'s childhood fears' },
      { title: 'Heaven Sent', year: 2015, type: 'episode', significance: 'Solo Doctor story, billions of years in the confession dial', isLandmark: true },
      { title: 'World Enough and Time/The Doctor Falls', year: 2017, type: 'episode', significance: 'Origin of Cybermen, two Masters, Bill\'s fate', isLandmark: true },
      { title: 'Twice Upon a Time', year: 2017, type: 'special', significance: 'Twelfth Doctor regenerates meeting the First', isLandmark: true },
    ],
    facts: [
      'Peter Capaldi was a lifelong Doctor Who fan',
      'No romantic plots with companions',
      'Played guitar in the TARDIS',
      'Era explored themes of mortality and legacy',
      'First openly punk rock Doctor',
    ],
    regenerationCause: 'Delayed regeneration after Cyberman battle, finally let go meeting the First Doctor',
  },
  {
    number: 13,
    name: 'Thirteenth Doctor',
    actor: 'Jodie Whittaker',
    years: '2018-2022',
    color: '#1d3557',
    accentColor: '#457b9d',
    personality: 'Optimistic, warm, curious. A friend to everyone with boundless enthusiasm.',
    catchphrase: 'Brilliant!',
    companions: [
      { name: 'Yasmin Khan', actor: 'Mandip Gill', description: 'Police officer from Sheffield', firstAppearance: 'The Woman Who Fell to Earth' },
      { name: 'Ryan Sinclair', actor: 'Tosin Cole', description: 'Warehouse worker with dyspraxia', firstAppearance: 'The Woman Who Fell to Earth' },
      { name: 'Graham O\'Brien', actor: 'Bradley Walsh', description: 'Bus driver, Ryan\'s step-grandfather', firstAppearance: 'The Woman Who Fell to Earth' },
      { name: 'Dan Lewis', actor: 'John Bishop', description: 'Liverpudlian museum worker', firstAppearance: 'The Halloween Apocalypse' },
    ],
    enemies: [
      { name: 'The Master (Sacha Dhawan)', description: 'O, the spy, destroyed Gallifrey', notableEpisodes: ['Spyfall', 'The Timeless Children', 'The Power of the Doctor'] },
      { name: 'Daleks', description: 'Recurring threat', notableEpisodes: ['Resolution', 'Revolution of the Daleks', 'Eve of the Daleks'] },
      { name: 'Cybermen', description: 'Lone Cyberman and Cyber-Masters', notableEpisodes: ['Ascension of the Cybermen', 'The Timeless Children'] },
      { name: 'The Flux', description: 'Universe-destroying antimatter wave', notableEpisodes: ['Flux series'] },
      { name: 'The Ravagers', description: 'Swarm and Azure', notableEpisodes: ['Flux series'] },
    ],
    keyStories: [
      { title: 'The Woman Who Fell to Earth', year: 2018, type: 'episode', significance: 'First female Doctor\'s debut', isLandmark: true },
      { title: 'Rosa', year: 2018, type: 'episode', significance: 'Civil rights historical with Rosa Parks' },
      { title: 'The Timeless Children', year: 2020, type: 'episode', significance: 'Reveals the Timeless Child - the Doctor\'s origin', isLandmark: true },
      { title: 'Flux', year: 2021, type: 'serial', significance: 'Six-part epic destroying the universe' },
      { title: 'The Power of the Doctor', year: 2022, type: 'special', significance: 'Thirteenth Doctor regenerates, multiple past Doctors appear', isLandmark: true },
    ],
    facts: [
      'First female Doctor',
      'Traveled with "fam" - largest TARDIS team in new era',
      'Discovered she was the Timeless Child',
      'Era included Flux serialized storytelling',
      'Regenerated into a previous face (Tennant)',
    ],
    regenerationCause: 'Forced regeneration by the Master using Cyber-conversion energy',
  },
  {
    number: 14,
    name: 'Fourteenth Doctor',
    actor: 'David Tennant',
    years: '2023',
    color: '#774936',
    accentColor: '#d4a276',
    personality: 'Returning face dealing with unprocessed trauma. Finally learning to rest.',
    catchphrase: 'What? What?! WHAT?!',
    companions: [
      { name: 'Donna Noble', actor: 'Catherine Tate', description: 'Returned with memories restored, DoctorDonna', firstAppearance: 'The Runaway Bride' },
      { name: 'Rose Noble', actor: 'Yasmin Finney', description: 'Donna\'s transgender daughter who inherited the meta-crisis', firstAppearance: 'The Star Beast' },
    ],
    enemies: [
      { name: 'The Meep', description: 'Cute but psychopathic alien', notableEpisodes: ['The Star Beast'] },
      { name: 'The Toymaker', description: 'God-like being who plays games', notableEpisodes: ['The Giggle'] },
      { name: 'The Not-Things', description: 'Creatures from the edge of the universe', notableEpisodes: ['Wild Blue Yonder'] },
    ],
    keyStories: [
      { title: 'The Star Beast', year: 2023, type: 'special', significance: '60th anniversary special, Donna returns' },
      { title: 'Wild Blue Yonder', year: 2023, type: 'special', significance: 'Horror two-hander at the edge of creation' },
      { title: 'The Giggle', year: 2023, type: 'special', significance: 'Bi-generation creates two Doctors simultaneously', isLandmark: true },
    ],
    facts: [
      'First Doctor to return to a previous face',
      'Result of bi-generation - split into two Doctors',
      'Finally got to rest with Donna\'s family',
      'Acknowledged past trauma needed healing',
      'Coexists with the Fifteenth Doctor',
    ],
    regenerationCause: 'Bi-generation - split into two separate Doctors',
  },
  {
    number: 15,
    name: 'Fifteenth Doctor',
    actor: 'Ncuti Gatwa',
    years: '2023-present',
    color: '#e07a5f',
    accentColor: '#f4a261',
    personality: 'Joyful, emotionally open, stylish. A Doctor who has processed his trauma.',
    catchphrase: 'Let\'s go!',
    companions: [
      { name: 'Ruby Sunday', actor: 'Millie Gibson', description: 'Foundling raised by her grandmother, mysterious origins', firstAppearance: 'The Church on Ruby Road' },
    ],
    enemies: [
      { name: 'Goblins', description: 'Time-eating creatures', notableEpisodes: ['The Church on Ruby Road'] },
      { name: 'Sutekh', description: 'Returning Osiran god of death', notableEpisodes: ['The Legend of Ruby Sunday', 'Empire of Death'] },
      { name: 'Maestro', description: 'The Toymaker\'s child, god of music', notableEpisodes: ['The Devil\'s Chord'] },
    ],
    keyStories: [
      { title: 'The Church on Ruby Road', year: 2023, type: 'special', significance: 'Fifteenth Doctor\'s first full story', isLandmark: true },
      { title: 'Space Babies', year: 2024, type: 'episode', significance: 'First regular episode of new Disney+ era' },
      { title: 'Empire of Death', year: 2024, type: 'episode', significance: 'Sutekh defeated, Ruby\'s mother revealed' },
    ],
    facts: [
      'First Black Doctor',
      'Born from bi-generation fully formed with his own TARDIS',
      'Partnership with Disney+ for global distribution',
      'Most emotionally available Doctor',
      'Era features returning classic villains',
    ],
  },
]

export function getDoctorByNumber(num: number): Doctor | undefined {
  return DOCTORS.find((d) => d.number === num)
}

export function getAllDoctors(): readonly Doctor[] {
  return DOCTORS
}

export function getDoctorColor(doctorNumber: number): string {
  return getDoctorByNumber(doctorNumber)?.color ?? '#003b6f'
}
